[package]
name = "Rust_Version"
version = "0.1.0"
authors = ["santoshpavan <santoshpavan.psp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"